# Generated by Django 4.2.7 on 2024-02-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_weather_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
